sudo: required

services:
  - docker

before_install:
  - docker build -t DamengRandom/docker-flow-with-ci-cd -f Dockerfile.dev .

script:
  - docker run DamengRandom/docker-flow-with-ci-cd yarn run test -- --coverage
